---
- name: "Install MariaDB"
  apt:
    name: mariadb-server
    state: present
    install_recommends: yes

# Set up database for p2 push component (Android)
- name: "Create database (p2)"
  become: yes
  mysql_db:
    name: snikket_push
    encoding: utf8mb4
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
- name: "Create p2 database user"
  become: yes
  mysql_user:
    name: p2
    password: "{{ lookup('password', 'credentials/p2_db length=32') }}"
    priv: "snikket_push.*:ALL"
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock

# Set up database for Tigase push component (iOS)
- name: "Create database (ios)"
  become: yes
  mysql_db:
    name: snikket_push_ios
    encoding: utf8mb4
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
- name: "Create ios database user"
  become: yes
  mysql_user:
    name: ios_push
    password: "{{ lookup('password', 'credentials/ios_push_db length=32') }}"
    priv: "snikket_push_ios.*:ALL"
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
