---
- name: "Install MariaDB"
  apt:
    name: mariadb-server
    state: present
    install_recommends: yes
- name: "Create database"
  become: yes
  mysql_db:
    name: snikket_push
    encoding: utf8mb4
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
- name: "Create p2 database user"
  become: yes
  mysql_user:
    name: p2
    password: "{{ lookup('password', 'credentials/p2_db length=32') }}"
    priv: "snikket_push.*:ALL"
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
